# Generated by Django 6.1 on 2026-09-29 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('receipts', '0002_receipt_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='invoices.invoice'),
        ),
    ]
