# Generated by Django 6.1 on 2026-08-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_logo_business_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
