# Generated by Django 6.1 on 2026-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='primary_color',
            field=models.CharField(default='#1F4E79', max_length=7),
        ),
        migrations.AddField(
            model_name='business',
            name='secondary_color',
            field=models.CharField(default='#F59E0B', max_length=7),
        ),
    ]
