# Generated by Django 6.1 on 2026-08-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('services', '0002_servicerecord_delete_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='businesses.business'),
        ),
    ]
