# Generated by Django 6.1 on 2026-09-25 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_business_primary_color_business_secondary_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counter', to='businesses.business')),
            ],
        ),
    ]
