# Generated by Django 6.1 on 2026-09-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_primary_color_business_secondary_color'),
        ('usage_limits', '0002_add_usage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('service', 'Service'), ('customer', 'Customer'), ('quotation', 'Quotation'), ('invoice', 'Invoice'), ('receipt', 'Receipt')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
            ],
        ),
    ]
